#!bash

# Install oh-my-zsh
#sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

rm -f ${HOME}/.zshrc
rm -f ${HOME}/.gitconfig
rm -f ${HOME}/.gitexcludes

ln -s ${PWD}/_zshrc ${HOME}/.zshrc
ln -s ${PWD}/_gitconfig ${HOME}/.gitconfig
ln -s ${PWD}/_gitexcludes ${HOME}/.gitexcludes
ln -s ${PWD}/nvim ${HOME}/.config/nvim
